export const menuData = [
{ id: 1, name: "Kopi Hitam", kategori: "Minuman", harga: 6000, tersedia: true, img: "☕" },
{ id: 2, name: "Pancong Lumer Keju Coklat", kategori: "Pancong", harga: 14000, tersedia: false, img: "🧇" },
  { id: 3, name: "Good Day Freeze", kategori: "Minuman", harga: 7000, tersedia: true, img: "🥤" },
  { id: 4, name: "Magelangan", kategori: "Magelangan", harga: 12000, tersedia: true, img: "🍜" },
  { id: 5, name: "Internet Rebus", kategori: "Mie Rebus", harga: 18000, tersedia: true, img: "🍝" },
  { id: 6, name: "Kopi Susu", kategori: "Minuman", harga: 10000, tersedia: true, img: "☕" },
  { id: 7, name: "Teh Tarik", kategori: "Minuman", harga: 8000, tersedia: true, img: "🧋" },
  { id: 3, name: "Good Day Freeze", kategori: "Minuman", harga: 8000, tersedia: true, img: "🥤" },
  { id: 4, name: "Magelangan", kategori: "Magelangan", harga: 18000, tersedia: true, img: "🍜" },
  { id: 5, name: "Internet Rebus", kategori: "Mie Rebus", harga: 12000, tersedia: true, img: "🍝" },
  { id: 6, name: "Kopi Susu", kategori: "Minuman", harga: 9000, tersedia: true, img: "☕" },
  { id: 7, name: "Teh Tarik", kategori: "Minuman", harga: 7000, tersedia: true, img: "🧋" },
{ id: 8, name: "Pancong Tiramisu", kategori: "Pancong", harga: 13000, tersedia: true, img: "🧇" },
  { id: 9, name: "Nasi Goreng", kategori: "Nasi", harga: 15000, tersedia: true, img: "🍳" },
  { id: 10, name: "Indomie Rebus Telur", kategori: "Mie Rebus", harga: 12000, tersedia: true, img: "🍝" },
  { id: 9, name: "Nasi Goreng Mentega Original", kategori: "Nasi", harga: 13000, tersedia: true, img: "🍳" },
  { id: 10, name: "Indomie Rebus Telur", kategori: "Mie Rebus", harga: 10000, tersedia: true, img: "🍝" },
  { id: 11, name: "Cappucino", kategori: "Minuman", harga: 8000, tersedia: true, img: "🥤"},
  { id: 12, name: "Air Putih", kategori: "Minuman", harga: 4000, tersedia:true, img: "🥤"},
  { id: 13, name: "Susu Jahe", kategori: "Minuman", harga: 9000, tersedia: true, img: "🥤"},
  { id: 14, name: "Es Teh Manis", kategori: "Minuman", harga: 4000, tersedia: true, img: "🥤"},
  { id: 15, name: "Nutrisari", kategori: "Minuman", harga: 6000, tersedia: true, img: "🥤"},
  { id: 16, name: "Dancow", kategori: "Minuman", harga: 9000, tersedia: true, img: "🥤"},
  { id: 17, name: "Soda Susu", kategori: "Minuman", harga: 9000, tersedia: true, img: "🥤"},
  { id: 18, name: "Chocolatos Matcha", kategoti: "Minuman", harga: 9000, tersedia: true, img: "🥤"},
  { id: 19, name: "Pancong Susu Oreo", kategori: "Pancong", harga: 13000, tersedia: true, img: "🧇"},
  { id: 20, name: "Pancong Lumer Matcha", kategori: "Pancong", harga: 13000, tersedia: true, img: "🧇"},
  { id: 21, name: "Pancong Coklat", kategori: "Pancong", harga: 13000, tersedia: true, img: "🧇"},
  { id: 22, name: "Pancong Choco Crunchy", kategori: "Pancong", harga: 14000, tersedia: true, img: "🧇"},
  { id: 23, name: "Nasi Putih", kategori: "Nasi", harga: 5000, tersedia: true, img: "🍳"},
  { id: 24, name: "Nasi Ayam Geprek", kategori: "Nasi", harga: 15000, tersedia: true, img: "🍳"},
  { id: 25, name: "Nasi Dadar Telur", kategori: "Nasi", harga: 9000, tersedia: true, img: "🍳"},
  { id: 26, name: "Nasi Goreng Mentega Ayam Suir", kategori: "Nasi", harga: 14000, tersedia: true, img: "🍳"},
  { id: 27, name: "Nasi Goreng Mentega Bakso", kategori: "Nasi", harga: 10000, tersedia: true, img: "🍳"},
  { id: 28, name: "Nasi + Omlete", kategori: "Nasi", harga: 18000, tersedia: true, img: "🍳"},
  { id: 29, name: "Nasi + Omlete Bakso", kategori: "Nasi", harga: 20000, tersedia: true, img: "🍳"},
  { id: 30, name: "Nasi + Omlete Ayam", kategori: "Nasi", harga: 22000, tersedia: true, img: "🍳"},
  { id: 31, name: "Nasi + Sarden", kategori: "Nasi", harga: 10000, tersedia: true, img: "🍳"},
  { id: 32, name: "Nasi Ayam Serundeng", kategori: "Nasi", harga: 20000, tersedia: true, img: "🍳"},
  { id: 33, name: "Nasi + Sarden Telur", kategori: "Nasi", harga: 14000, tersedia: true, img: "🍳"},
  { id: 34, name: "Nasi Ayam Serundeng Paru", kategori: "Nasi", harga: 28000, tersedia: true, img: "🍳"},
  { id: 35, name: "Nasi Ayam Serundeng Ati Ampela", kategori: "Nasi", harga: 25000, tersedia: true, img: "🍳"},
  { id: 36, name: "Nasi Kulit Serundeng", kategori: "Nasi", harga: 13000, tersedia: true, img: "🍳"},
  { id: 37, name: "Nasi Kulit Paru Serundeng", kategori: "Nasi", harga: 20000, tersedia: true, img: "🍳"},
  { id: 38, name: "Magelangan Extra Nasi", kategori: "Magelangan", harga: 20000, tersedia: true, img: "🍜"},
  { id: 39, name: "Magelangan Bakso", kategori: "Magelangan", harga: 21000, tersedia: true, img: "🍜"},
  { id: 40, name: "Magelangan Ayam Suir", kategori: "Magelangan", harga: 25000, tersedia: true, img: "🍜"},
  { id: 41, name: "Magelangan Bakso Sosis", kategori: "Magelangan", harga: 24000, tersedia: true, img: "🍜"},
  { id: 42, name: "Magelangan Kornet", kategori: "Magelangan", harga: 22000, tersedia: true, img: "🍜"},
  { id: 43, name: "Magelangan Nugget", kategori: "Magelangan", harga: 20000, tersedia: true, img: "🍜"},
  { id: 44, name: "Magelangan Telur Dadar", kategori: "Magelangan", harga: 23000, tersedia: true, img: "🍜"},
  { id: 45, name: "Magelangan Telur Ceplok", kategori: "Magelangan", harga: 23000, tersedia: true, img: "🍜"},
  { id: 46, name: "Magelangan Telur Orak Arik", kategori: "Magelangan", harga: 23000, tersedia: true, img: "🍜"},
  { id: 47, name: "Indomie Goreng Telur", kategori: "Magelangan", harga: 10000, tersedia: true, img: "🍜"},
  { id: 48, name: "Indomie Goreng Double", kategori: "Magelangan", harga: 12000, tersedia: true, img: "🍜"},
  { id: 49, name: "Indomie Goreng Keju", kategori: "Magelangan", harga: 10000, tersedia: true, img: "🍜"},
  { id: 50, name: "Internet Goreng", kategori: "Magelangan", harga: 12000, tersedia: true, img: "🍜"},
  { id: 51, name: "Indomie Rebus Double", kategori: "Mie Rebus", harga: 12000, tersedia: true, img: "🍝"},
  { id: 52, name: "Indomie Rebus Bakso", kategori: "Mie Rebus", harga: 9000, tersedia: true, img: "🍝"},
  { id: 53, name: "Indomie Rebus Sosis", kategori: "Mie Rebus", harga: 9000, tersedia: true, img: "🍝"},
  { id: 54, name: "Indomie Rebus Ayam Suir", kategori: "Mie Rebus", harga: 11000, tersedia: true, img: "🍝"},
  { id: 55, name: "Indomie Rebus Keju", kategori: "Mie Rebus", harga: 10000, tersedia: true, img: "🍝"},
  { id: 56, name: "Bubur Kacang Hijau", kategori: "Bubur", harga: 9000, tersedia: true, img: "🍚"},
  { id: 57, name: "Bubur Kacang Hijau + Ketan Hitam", kategori: "Bubur", harga: 9000, tersedia: true, img: "🍚"},
  { id: 58, name: "Bubur Kacang Hijau Keju", kategori: "Bubur", harga: 13000, tersedia: true, img: "🍚"},
  { id: 59, name: "Bubur Kacang Hijau Dancow", kategori: "Bubur", harga: 14000, tersedia: true, img: "🍚"},
  { id: 60, name: "Bubur Ketan Hitam", kategori: "Bubur", harga: 9000, tersedia: true, img: "🍚"},
  { id: 61, name: "Bubur Ketan Hitam Keju", kategori: "Bubur", harga: 13000, tersedia: true, img: "🍚"},
  { id: 62, name: "Pisang Bakar Coklat", kategori: "Pisang Bakar", harga: 10000, tersedia: true, img: "🍌"},
  { id: 63, name: "Pisang Bakar Coklat Keju", kategori: "Pisang Bakar", harga: 13000, tersedia: true, img: "🍌"},
  { id: 64, name: "Pisang Bakar Oreo Susu", kategori: "Pisang Bakar", harga: 15000, tersedia: true, img: "🍌"},
  { id: 65, name: "Pisang Bakar Choco Crunchy", kategori: "Pisang Bakar", harga: 14000, tersedia: true, img: "🍌"},
  { id: 66, name: "Pisang Bakar Strawberry", kategori: "Pisang Bakar", harga: 14000, tersedia: true, img: "🍌"},
  { id: 67, name: "Pisang Bakar Tiramisu", kategori: "Pisang Bakar", harga: 14000, tersedia: true, img: "🍌"},
  { id: 68, name: "Pisang Bakar Green Tea", kategori: "Pisang Bakar", harga: 14000, tersedia: true, img: "🍌"},
  { id: 69, name: "Pisang Bakar Hazelnut Crunchy", kategori: "Pisang Bakar", harga: 14000, tersedia: true, img: "🍌"}

];

export const stokData = [
  { id: 1, name: "Kopi Hitam", kategori: "Minuman", jumlah: 42 },
  { id: 2, name: "Pancong Lumer Keju Coklat", kategori: "Pancong", jumlah: 4 },
  { id: 3, name: "Good Day Freeze", kategori: "Minuman", jumlah: 0 },
  { id: 4, name: "Magelangan", kategori: "Magelangan", jumlah: 3 },
  { id: 5, name: "Internet Rebus", kategori: "Mie Rebus", jumlah: 5 },
  { id: 6, name: "Kopi Susu", kategori: "Minuman", jumlah: 5 },
  { id: 7, name: "Nasi Goreng", kategori: "Nasi", jumlah: 3 },
  { id: 8, name: "Cappuccino", kategori: "Minuman", jumlah: 0 },
  { id: 9, name: "Teh Tarik", kategori: "Minuman", jumlah: 22 },
  { id: 10, name: "Indomie Goreng", kategori: "Mie Goreng", jumlah: 18 },
  { id: 1, name: "Kopi Hitam", kategori: "Minuman", jumlah: 5},
  { id: 2, name: "Pancong Lumer Keju Coklat", kategori: "Pancong", jumlah: 0},
  { id: 3, name: "Good Day Freeze", kategori: "Minuman", jumlah: 42},
  { id: 4, name: "Magelangan", kategori: "Magelangan", jumlah: 3},
  { id: 5, name: "Internet Rebus", kategori: "Mie Rebus", jumlah: 4},
  { id: 6, name: "Kopi Susu", kategori: "Minuman", jumlah: 11},
  { id: 7, name: "Teh Tarik", kategori: "Minuman", jumlah: 9},
  { id: 8, name: "Pancong Tiramisu", kategori: "Pancong", jumlah: 15},
  { id: 9, name: "Nasi Goreng Mentega Original", kategori: "Nasi", jumlah: 12},
  { id: 10, name: "Indomie Rebus Telur", kategori: "Mie Rebus", jumlah: 30},
  { id: 11, name: "Cappucino", kategori: "Minuman", jumlah: 15},
  { id: 12, name: "Air Putih", kategori: "Minuman", jumlah: 22},
  { id: 13, name: "Susu Jahe", kategori: "Minuman", jumlah: 13},
  { id: 14, name: "Es Teh Manis", kategori: "Minuman", jumlah: 25},
  { id: 15, name: "Nutrisari", kategori: "Minuman", jumlah: 18},
  { id: 16, name: "Dancow", kategori: "Minuman", jumlah: 20},
  { id: 17, name: "Soda Susu", kategori: "Minuman", jumlah: 10},
  { id: 18, name: "Chocolatos Matcha", kategoti: "Minuman", jumlah: 15},
  { id: 19, name: "Pancong Susu Oreo", kategori: "Pancong", jumlah: 6},
  { id: 20, name: "Pancong Lumer Matcha", kategori: "Pancong", jumlah: 10},
  { id: 21, name: "Pancong Coklat", kategori: "Pancong", jumlah: 13},
  { id: 22, name: "Pancong Choco Crunchy", kategori: "Pancong", jumlah: 19},
  { id: 23, name: "Nasi Putih", kategori: "Nasi", jumlah: 25},
  { id: 24, name: "Nasi Ayam Geprek", kategori: "Nasi", jumlah: 16},
  { id: 25, name: "Nasi Dadar Telur", kategori: "Nasi", jumlah: 17},
  { id: 26, name: "Nasi Goreng Mentega Ayam Suir", kategori: "Nasi", jumlah: 12},
  { id: 27, name: "Nasi Goreng Mentega Bakso", kategori: "Nasi", jumlah: 14},
  { id: 28, name: "Nasi + Omlete", kategori: "Nasi", jumlah: 18},
  { id: 29, name: "Nasi + Omlete Bakso", kategori: "Nasi", jumlah: 19},
  { id: 30, name: "Nasi + Omlete Ayam", kategori: "Nasi", jumlah: 12},
  { id: 31, name: "Nasi + Sarden", kategori: "Nasi", jumlah: 11},
  { id: 32, name: "Nasi Ayam Serundeng", kategori: "Nasi", jumlah: 11},
  { id: 33, name: "Nasi + Sarden Telur", kategori: "Nasi", jumlah: 10},
  { id: 34, name: "Nasi Ayam Serundeng Paru", kategori: "Nasi", jumlah: 4},
  { id: 35, name: "Nasi Ayam Serundeng Ati Ampela", kategori: "Nasi", jumlah: 2},
  { id: 36, name: "Nasi Kulit Serundeng", kategori: "Nasi", jumlah: 7},
  { id: 37, name: "Nasi Kulit Paru Serundeng", kategori: "Nasi", jumlah: 10},
  { id: 38, name: "Magelangan Extra Nasi", kategori: "Magelangan", jumlah: 14},
  { id: 39, name: "Magelangan Bakso", kategori: "Magelangan", jumlah: 15},
  { id: 40, name: "Magelangan Ayam Suir", kategori: "Magelangan", jumlah: 12},
  { id: 41, name: "Magelangan Bakso Sosis", kategori: "Magelangan", jumlah: 9},
  { id: 42, name: "Magelangan Kornet", kategori: "Magelangan", jumlah: 10},
  { id: 43, name: "Magelangan Nugget", kategori: "Magelangan", jumlah: 11},
  { id: 44, name: "Magelangan Telur Dadar", kategori: "Magelangan", jumlah: 15},
  { id: 45, name: "Magelangan Telur Ceplok", kategori: "Magelangan", jumlah: 17},
  { id: 46, name: "Magelangan Telur Orak Arik", kategori: "Magelangan", jumlah: 15},
  { id: 47, name: "Indomie Goreng Telur", kategori: "Magelangan", jumlah: 19},
  { id: 48, name: "Indomie Goreng Double", kategori: "Magelangan", jumlah: 20},
  { id: 49, name: "Indomie Goreng Keju", kategori: "Magelangan", jumlah: 12},
  { id: 50, name: "Internet Goreng", kategori: "Magelangan", jumlah: 3},
  { id: 51, name: "Indomie Rebus Double", kategori: "Mie Rebus", jumlah: 9},
  { id: 52, name: "Indomie Rebus Bakso", kategori: "Mie Rebus", jumlah: 7},
  { id: 53, name: "Indomie Rebus Sosis", kategori: "Mie Rebus", jumlah: 8},
  { id: 54, name: "Indomie Rebus Ayam Suir", kategori: "Mie Rebus", jumlah: 13},
  { id: 55, name: "Indomie Rebus Keju", kategori: "Mie Rebus", jumlah: 9},
  { id: 56, name: "Bubur Kacang Hijau", kategori: "Bubur", jumlah: 9},
  { id: 57, name: "Bubur Kacang Hijau + Ketan Hitam", kategori: "Bubur", jumlah: 12},
  { id: 58, name: "Bubur Kacang Hijau Keju", kategori: "Bubur", jumlah: 11},
  { id: 59, name: "Bubur Kacang Hijau Dancow", kategori: "Bubur", jumlah: 7},
  { id: 60, name: "Bubur Ketan Hitam", kategori: "Bubur", jumlah: 15},
  { id: 61, name: "Bubur Ketan Hitam Keju", kategori: "Bubur", jumlah: 4},
  { id: 62, name: "Pisang Bakar Coklat", kategori: "Pisang Bakar", jumlah: 13},
  { id: 63, name: "Pisang Bakar Coklat Keju", kategori: "Pisang Bakar", jumlah: 17},
  { id: 64, name: "Pisang Bakar Oreo Susu", kategori: "Pisang Bakar", jumlah: 9},
  { id: 65, name: "Pisang Bakar Choco Crunchy", kategori: "Pisang Bakar", jumlah: 7},
  { id: 66, name: "Pisang Bakar Strawberry", kategori: "Pisang Bakar", jumlah: 5},
  { id: 67, name: "Pisang Bakar Tiramisu", kategori: "Pisang Bakar", jumlah: 14},
  { id: 68, name: "Pisang Bakar Green Tea", kategori: "Pisang Bakar", jumlah: 10},
  { id: 69, name: "Pisang Bakar Hazelnut Crunchy", kategori: "Pisang Bakar", jumlah: 13}

];

export const transaksiData = [
{ kode: "#RFW00042", meja: "Meja 4", item: "Kopi Hitam, Internet Rebus", total: 18000, waktu: "20:15", metode: "QRIS", status: "Selesai" },
{ kode: "#RFW00043", meja: "Meja 2", item: "Magelangan, Good Day Freeze", total: 26000, waktu: "20:09", metode: "Tunai", status: "Selesai" },
{ kode: "#RFW00044", meja: "Meja 6", item: "Pancong Lumer Keju Coklat", total: 14000, waktu: "20:01", metode: "QRIS", status: "Diproses" },
{ kode: "#RFW00045", meja: "Meja 3", item: "Pancong Tiramisu", total: 13000, waktu: "19:52", metode: "Tunai", status: "Selesai" },
{ kode: "#RFW00046", meja: "Meja 7", item: "Teh Tarik, Indomie Rebus Telur", total: 17000, waktu: "19:44", metode: "QRIS", status: "Selesai" },
{ kode: "#RFW00047", meja: "Meja 1", item: "Pancong Tiramisu, Kopi Susu", total: 22000, waktu: "20:30", metode: "Tunai", status: "Baru" },
{ kode: "#RFW00048", meja: "Meja 9", item: "Pancong Lumer Keju Coklat, Air Putih", total: 18000, waktu: "18:01", metode: "QRIS", status: "Diproses" },
{ kode: "#RFW00049", meja: "Meja 5", item: "Magelangan, Air Putih", total: 22000, waktu: "19:30", metode: "QRIS", status: "Baru" },
{ kode: "#RFW00050", meja: "Meja 8", item: "Indomie Goreng Keju", total: 10000, waktu: "19:59", metode: "Tunai", status: "Diproses" },
{ kode: "#RFW00051", meja: "Meja 5", item: "Kopi Susu, Nasi Goreng", total: 25000, waktu: "21:00", metode: "QRIS", status: "Selesai" },
];
